network_name = "ethereum"
endpoint = "https://api.etherscan.io/api"
api_key = "ETHERSCAN_API_KEY"             # loaded from .env

coin_symbol = "ETH"

[[tokens]]
name = "Tether USD"
symbol = "USDT"
address = "0xdac17f958d2ee523a2206206994597c13d831ec7"

[[tokens]]
name = "USD Coin"
symbol = "USDC"
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"

[[tokens]]
name = "Dai"
symbol = "DAI"
address = "0x6b175474e89094c44da98b954eedeac495271d0f"
